### ISSUE TITLE
We don't execute document.execCommand() this time, because it is called recursively.

### ISSUE THREAD

**Issue by sangdth** [CharlesStover/use-clippy#12]
I got this problem on Chrome. My app is quite complex thus I do not know which part causes this.

nwjs/nw.js/issues/3403

**Comment by CharlesStover** [comment]
I have not seen this error before, so I am not sure without a minimal reproduction. My guess is that your Component re-rendering is attempting to set the clipboard.

Setting the clipboard causes a re-render, because the first parameter of `useClippy` is the current clipboard value.

If you are setting the clipboard on render, this can trigger an infinite loop. This error may be Chrome bailing out of that loop.

Potential areas of interest:
On line 115, we execute the copy command: https://github.com/CharlesStover/use-clippy/blob/master/src/use-clippy.ts#L115
On line 141, we listen for the copy event and rerender when it occurs: https://github.com/CharlesStover/use-clippy/blob/master/src/use-clippy.ts#L141
On line 177, we execute the copy command and also re-render: https://github.com/CharlesStover/use-clippy/blob/master/src/use-clippy.ts#L177

While this, at worst, should just result in two re-renders instead of one, there may be funky logic here that causes Chrome to think the clipboard is being accessed too frequently.

I would first investigate that you aren't just setting the clipboard on each render.

**Comment by sangdth** [comment]
Thanks for your response, I don't have time to investigate deeper, I'm using another similar hook from `react-use` package and it works ok now.
