### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by CDAracena** [CharlesStover/use-clippy#17]
Thought it would work for multiple browsers, does it currently only work for Chrome ?

Chrome is reading the clipboard correctly, Safari returns an empty string.

**Comment by CharlesStover** [comment]
It uses more than one clipboard API, so it should work for more than just Chrome, but Safari is not officially supported, as I am a Windows developer. I would welcome a pull request for support.

**Comment by dimitriharding** [comment]
@CDAracena Which version of Safari was that? use-clippy does work for me in Safari (Version 13.1 ). I am having another issue where I am having a paste prompt when `setClipboard` is called, if I select paste then the data is copied to the clipboard. 

![Screen Shot 2020-05-04 at 10.29.58 PM.png](https://seetyah.s3.amazonaws.com/Screen%20Shot%202020-05-04%20at%2010.29.58%20PM.png)

@CharlesStover I would be interested in submitting a PR, but what are the local testing instructions?

**Comment by CharlesStover** [comment]
There are shamefully no tests. This was a PoC I made for either a Reddit or Twitter user to show how to make a native browser API stateful. It ended up being pretty powerful, so I just published it as-is.

It's kind of difficult to test native browser APIs in a Node test environment, but it should be done nonetheless.

I will close this issue as you have verified that Safari works, which is what I would expect given the different clipboard APIs supported by this hook.

I'd also be willing to help your issue with your paste prompt, but please open another issue so I may tag it as `support` instead of a feature request.

What PR are you considering submitting (given Safari is supported)?
