### ISSUE TITLE
image support?

### ISSUE THREAD

**Issue by khrishan** [CharlesStover/use-clippy#23]
Does `use-clippy` work with images?

I've tried using it in my project, but I'm having no luck.

Wanted to check if this would be a feature request / something you are looking at - or is this out of scope?

Great little utility otherwise 👍

**Comment by CharlesStover** [comment]
That's a really cool idea, but unfortunately it would be out of scope. As much as I'd like to see it, this package integrates with the browser's Clipboard API, which I don't believe supports that feature. To add support would be adding a separate feature which would amount to a separate hook, which would be most fitting as a separate package, instead of one package that does too many things.
