### ISSUE TITLE
Only write permissions version

### ISSUE THREAD

**Issue by alexbu92** [CharlesStover/use-clippy#26]
I only need to be able to put a string in the user's clipboard in my project, if there was a hypothetical clippy version with only write functionality would it avoid the need for the user to give permission to the site to read the clipboard's contents? It would be nice to reduce friction for the user.

**Comment by Far3t** [comment]
I'm also looking for something like that, so bumping a little bit your issue to see if there are some answers about that.
Or did you find another way to do it?

**Comment by asaf** [comment]
comment out those lines:

```
addEventListener(type: 'cut', eventListener: ClipboardEventListener): void
removeEventListener(type: 'cut', eventListener: ClipboardEventListener): void
navigator.clipboard.addEventListener('cut', clipboardListener)
navigator.clipboard.removeEventListener('cut', clipboardListener)
```

**Comment by CharlesStover** [comment]
I am not positive that a write-only permissions version would need to be a hook. A write-only permissions version wouldn't be stateful -- it wouldn't respond to state changes or trigger a re-render of the component.

This feature sounds best implemented simply as a function.

I'm not opposed to the write feature within `use-clippy` being abstracted to a separate package for simply writing, and `use-clippy` relying on that module for its write functionality; but I don't think a write-only implementation of `use-clippy` makes sense as a hook since it would not be stateful.

Feel free to discuss if I am missing something. :)
