### ISSUE TITLE
Unwanted side effects in Safari

### ISSUE THREAD

**Issue by arturlagutin** [CharlesStover/use-clippy#4]
Nice lib! However it does have an unwanted side effect in Safari: it scrolls the window down a bit for some reason.

**Comment by CharlesStover** [comment]
Can you provide a repo/CodeSandbox with a minimum reproduction?

**Comment by arturlagutin** [comment]
Sorry, just wanted to report this hoping that someone will figure this out without any additional info from my side. Don't want to be a dick, but I'm pretty sure it's reproducible quite simply. Just bootstrap some app, create a long page with scroll, and try it in Safari.

**Comment by CharlesStover** [comment]
Safari is no longer supported on Windows, so I cannot test this myself.

Without more information or other reports, I'll close this for cleaning but welcome PRs if it becomes solvable in the future.

**Comment by kevinkam** [comment]
Hi @arturlagutin I can simulate your issue on my iPhone safari, I tried to fix this issue, and found that this issue is cause by the input is append at the bottom of the body and focus it.
So I change to prepend the input to the body, then it comes up another issue, because it's focusing an input field, the keyboard also comes up when I try to copy, then I set the input to readOnly, but it still showing "Paste/Speak", this one I really don't know how to solve.
